import Head from "next/head";

import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className='w-full flex flex-col items-center'>
			<Head>
				<title>fam RunSys Pokemon</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className='bg-slate-700 w-full flex flex-col justify-center items-center max-w-6xl'>
        <h1 className="text-3xl font-bold">fam Runsys Pokemon</h1>
        <p>fam Runsys Pokemon</p>
      </main>
		</div>
	);
}
